GAMETITLE = "Pokemon Reborn"
GAMEVERSION = "e19.07"
Reborn = true
Desolation = false
Rejuv = false

LEVELCAPS          = [20,25,35,40,45,50,55,60,65,70,70,75,75,80,85,90,90,95,150]
STARTINGMAP        = 51

#===============================================================================
# * Two hashes for Variables and Switch names, in ascending order
#===============================================================================
Switches = {
    Seen_Pokerus:                 	2,
    Starting_Over:                	5,
    Force_Weather:                	151,
    Force_Wild_Shiny:             	261,
    Fateful_Encounter:            	262,
    No_Catching:                  	290,
    Riding_Tauros:                	291,
	HearPinsir_Puzzle:				391,
    No_Mega_Evolution:            	407,
    Has_PokeSnax:                 	414,
    No_Bump:                      	420,
    Pulse_Evolution:              	457,
    Rage_Powder_Vial:             	463,
    Sleep_Powder_Vial:            	464,
    Reborn_City_Restore:          	479,
	Egg_Trade:						540,
    Wall_Smash:                   	568,
    Faux_Surf:                    	578,
	Pulse_Dex:						586,
	Field_Notes:					599,
	Retain_Surf:					649,
	Application_Applied:			715,
	Egg_Trade_2:					732,
	Anna_Smiles:					735,
    Devon_Panel_Switch:           	745,
    Devon_Panel_Puzzle:           	779,
	Get_A_Job_Quest:				783,
    No_Money_Loss:                	789,
    No_Z_Move:                    	790,
    Cant_Surf:                    	850,
    Last_Ace_Switch:              	1000,
	Magic_Square_Done:				1028,
	Dex_Quest_Done:					1043,
	Wing_Dings:						1060,

    Never_Escape:                 	1080,
    Show_Department_Card:         	1097,
    Rock_Climb_Convenience:       	1100,
    Stop_Icycle_Falling:          	1106,
    VR_Gem3:             		  	1179,
    Hard_Level_Cap:               	1180,
    Exp_All_On:                   	1181,
    Stop_Arrows_Shooting:         	1260,
	Pulse_Arceus:					1303,
	Disable_Quicksave:				1351,
    Grinding_Trainer_Money_Cut:   	1356,
	Nuzlocke_Mode:					1357,
    Penniless_Mode:               	1358,

    Randomized_Challenge:         	1361,
	EasyHMs_Password:				1362,
    Just_Budew:                   	1365,
    Only_Pulse_2:                 	1368,
    No_Items_Password:            	1369,
    Battle_Tower_FE_Enabled:       	1376,
    Blue_Orb_Quest:               	1674,
	Rayquaza_Roam:					1870,
    Level_999:                    	1942,
    Disable_Signposts_Music:      	2018,
	Empty_IVs_And_EVs_Password:		2038,		
    Moneybags:                    	2039,
    No_Damage_Rolls:              	2070,
    Full_IVs:                     	2076,
    Offset_Trainer_Levels:        	2077,
    Percent_Trainer_Levels:       	2102,
	Stable_Weather_Password:		2113,
    Overworld_Poison_Password:    	2118,
    Empty_IVs_Password:           	2119,
    Stop_Items_Password:          	2120,
    Just_Vulpix:                  	2122,
    In_Battle:                    	2123,
    Stop_Ev_Gain:                 	2130,
    Cut_Convenience:              	2132,
    Waterfall_Convenience:        	2133,
    Surf_Convenience:             	2134,
    Weather_password:             	2149,
	Mid_quicksave:					2150,
    Rock_Smash_Convenience:       	2152,
    Exp_All_Upgrade:              	2155,
	A_Fervent_Wish:					2158,
    Gen_5_Weather:                	2161,
	Inversemode:				    2177,
	Unreal_Time:				    2179,
	Free_Remote_PC:				    2182,
	Flat_EV_Password:				2191,
	No_Total_EV_Cap:				2192,
	VR_Gem4:						2194,
	VR_Gem5:						2195,
	NB_Pokemon_Only:				2205,
	No_EXP_Gain:					2207
}
Variables = {
	Field_Effect_End_Of_Battle:		7,
	Field_Counter_End_Of_Battle:	8,
	Weather_End_Of_Battle:			9,
	Cave_Collapse:                	10,
	Save_Slot:						27,
	Weather_Randomizer:				83,
	Current_Weather:				91,
	E10_Story:						150,
	Player_Gender:					151,
	Forced_Field_Effect:			161,
	Battle_Text_of_Opponent:		192,
	Next_Weather_Archetype:			317,
	Place_In_Weather_Pattern:		318,
	Starter_Quest:					438,
	Spirit_Rewards:					549,
	E4_Tracker:          			552,
	Randomized_File_Loc:          	565,
	Randomized_Pokemon:           	566,
	Randomized_Other:				567,
	Extended_Max_Level:				595,
	Xernyvel:						660,
	doublebattlefact:           	788,
	rentalsnew:						789,
	oldopponent:					790,
	opponentnew:					791
}

#===============================================================================
# * Message/Speech Frame location arrays
#=============================================================================

SpeechFrames=[
	"PRWS- speech1", # Default: speech hgss 1
	"PRWS- speech2",
	"PRWS- speech3",
	"PRWS- speech4",
	"PRWS- speech5",
	"PRWS- speech6",
	"PRWS- speech7",
	"PRWS- speech8",
	"PRWS- speech9",
	"PRWS- speech10",
	"PRWS- speech11",
	"PRWS- speech12",
	"PRWS- speech13",
	"PRWS- speech14",
	"PRWS- speech15",
	"PRWS- speech16",
	"PRWS- speech17",
	"PRWS- speech18",
	"PRWS- speech19",
	"PRWS- speech20",
	"PRWS- speech21",
	"PRWS- speech22",
	"PRWS- speech23",
	"PRWS- speech24",
	"PRWS- speech25",
	"PRWS- speech26",
	"PRWS- speech27",
	"PRWS- speech28"
]

TextFrames=[
	"Graphics/Windowskins/PRWS- menu1", # Default: choice 1
	"Graphics/Windowskins/PRWS- menu2",
	"Graphics/Windowskins/PRWS- menu3",
	"Graphics/Windowskins/PRWS- menu4",
	"Graphics/Windowskins/PRWS- menu5",
	"Graphics/Windowskins/PRWS- menu6",
	"Graphics/Windowskins/PRWS- menu7",
	"Graphics/Windowskins/PRWS- menu8",
	"Graphics/Windowskins/PRWS- menu9",
	"Graphics/Windowskins/PRWS- menu10",
	"Graphics/Windowskins/PRWS- menu11",
	"Graphics/Windowskins/PRWS- menu12",
	"Graphics/Windowskins/PRWS- menu13",
	"Graphics/Windowskins/PRWS- menu14",
	"Graphics/Windowskins/PRWS- menu15",
	"Graphics/Windowskins/PRWS- menu16",
	"Graphics/Windowskins/PRWS- menu17",
	"Graphics/Windowskins/PRWS- menu18",
	"Graphics/Windowskins/PRWS- menu19",
	"Graphics/Windowskins/PRWS- menu20",
	"Graphics/Windowskins/PRWS- menu21",
	"Graphics/Windowskins/PRWS- menu22",
	"Graphics/Windowskins/PRWS- menu23",
	"Graphics/Windowskins/PRWS- menu24",
	"Graphics/Windowskins/PRWS- menu25",
	"Graphics/Windowskins/PRWS- menu26",
	"Graphics/Windowskins/PRWS- menu27",
	"Graphics/Windowskins/PRWS- menu28"
]

VersionStyles=[
	["PokemonEmerald"]#, # Default font style - Power Green/"Pokemon Emerald"
	#["Power Red and Blue"],
	#["Power Red and Green"],
	#s["Power Clear"]
]
