begin
  class PBEffects
    # These effects apply to a battler - starts from 0
    AquaRing          = 0
    Attract           = 1
    Bide              = 2
    BideDamage        = 3
    BideTarget        = 4
    Charge            = 5
    ChoiceBand        = 6
    Confusion         = 7
    Counter           = 8
    CounterTarget     = 9
    Curse             = 10
    DefenseCurl       = 11
    DestinyBond       = 12
    Disable           = 13
    DisableMove       = 14
    EchoedVoice       = 15
    Embargo           = 16
    Encore            = 17
    EncoreIndex       = 18
    EncoreMove        = 19
    Endure            = 20
    FlashFire         = 21
    Flinch            = 22
    FocusEnergy       = 23
    FollowMe          = 24
    Foresight         = 25
    FuryCutter        = 26
    FutureSight       = 27
    FutureSightDamage = 28
    FutureSightMove   = 29
    FutureSightUser   = 30
    GastroAcid        = 31
    Grudge            = 32
    HealBlock         = 33
    HealingWish       = 34
    HelpingHand       = 35
    HyperBeam         = 36
    Imprison          = 37
    Ingrain           = 38
    LeechSeed         = 39
    LockOn            = 40
    LockOnPos         = 41
    LunarDance        = 42
    MagicCoat         = 43
    MagnetRise        = 44
    MeanLook          = 45
    Metronome         = 46
    Minimize          = 47
    MiracleEye        = 48
    MirrorCoat        = 49
    MirrorCoatTarget  = 50
#    MudSport          = 51
    MultiTurn         = 52 # Trapping move
    MultiTurnAttack   = 53
    MultiTurnUser     = 54
    Nightmare         = 55
    Outrage           = 56
    PerishSong        = 57
    PerishSongUser    = 58
    Pinch             = 59 # Battle Palace only
    PowerTrick        = 60
    Protect           = 61
    ProtectNegation   = 62
    ProtectRate       = 63
    Pursuit           = 64
    Rage              = 65
    Revenge           = 66
    Rollout           = 67
    Roost             = 68
    SkyDrop           = 69
    SmackDown         = 70
    Snatch            = 71
    Stockpile         = 72
    StockpileDef      = 73
    StockpileSpDef    = 74
    Substitute        = 75
    Taunt             = 76
    Telekinesis       = 77
    Torment           = 78
    Toxic             = 79
    Trace             = 80
    Transform         = 81
    Truant            = 82
    TwoTurnAttack     = 83
    Uproar            = 84
#    WaterSport        = 85
    WeightMultiplier  = 86
    Wish              = 87
    WishAmount        = 88
    WishMaker         = 89
    Yawn              = 90  
    Illusion          = 91 #Illusion
    StickyWeb         = 101
    KingsShield       = 102
    SpikyShield       = 103
    #Illusion          = 106
    FairyLockRate     = 107
    ParentalBond      = 108
    Round             = 109
    Powder            = 110
    Electrify         = 111
    MeFirst           = 112
    WideGuardCheck    = 113
    WideGuardUser     = 114  
    RagePowder        = 115
    MagicBounced      = 116
    TracedAbility     = 117
    UsingSubstituteRightNow = 118
    SkyDroppee        = 119
    DestinyRate       = 120
    BanefulBunker     = 121
    BeakBlast         = 122
    BurnUp            = 123
    ClangedScales     = 124
    LaserFocus        = 125
    ShellTrap         = 126
    SpeedSwap         = 127
    Tantrum           = 128
    ThroatChop        = 129
    Disguise          = 130
    ZHeal             = 131
    Blazed            = 132
    Savagery          = 133
    RampCrestUsage    = 134
    TyphBond          = 135
    VoreCopy          = 136
    NoRetreat         = 137
    BallFetch         = 138  
    IceFace           = 139
    ThunderRaidHit    = 140
    ThunderRaidStat   = 141
    TarShot           = 142  
    KinesisBoost      = 143  
    SusCrit           = 144  
    Obstruct          = 145
    Octolock          = 146
    # -1 = no stance, 0 = defense stance, 1 = attack stance
    VespiCrest       = 146
    DesertsMark       = 147
    Resusitated       = 147 # AMOGUS
    WillMega          = 148  
    WorldOfNightmares  = 149
    Petrification   = 150
    FeverPitch      = 151
    Attacking       = 152
    AttackingTarget = 153
    Switching       = 154
    SwitchingTo       = 155
    SomethingCrazy  = 156
    Switched        = 157
    CritCount       = 158
    UsingItem        = 159
    # These effects apply to a side - starts from 300
    LightScreen   = 300
    LuckyChant    = 301
    Mist          = 302
    Reflect       = 303
    Safeguard     = 304
    Spikes        = 305
    StealthRock   = 306
    Tailwind      = 307
    ToxicSpikes   = 308
    WideGuard     = 309
    QuickGuard    = 310
    Retaliate     = 311
    CraftyShield  = 312
    MatBlock      = 313
    AuroraVeil    = 314
    AreniteWall   = 315
    # These effects apply to the battle (i.e. both sides) - starts from 400
    Gravity       = 400
    MagicRoom     = 401
    #TrickRoom     = 402
    WonderRoom    = 403
    Terrain       = 404
    FairyLock     = 405
    IonDeluge     = 406
    # Additional weather effects
    HarshSunlight = 407
    HeavyRain     = 408
    MudSport      = 409
    WaterSport    = 410
    # V13 + Overlay Terrains - Grassy/Electric/Misty/Psychic
    GrassyTerrain = 501
    MistyTerrain = 502
    ElectricTerrain = 503
    PsychicTerrain = 504
    Splintered = 505
    Rainbow = 506
    # These effects apply to the usage of a move
    SpecialUsage = 701
    PassedTrying = 702
    TotalDamage  = 703
    ShieldLife   = 704
  end
rescue Exception
  if $!.is_a?(SystemExit) || "#{$!.class}"=="Reset"
    raise $!
  end
end